import os
import csv
import glob
import subprocess
import gradio as gr

MODEL_FILE = "/Users/vpartain/Desktop/WIP/mountain_lion_model.tflite"
OUTPUT_DIR = "/Users/vpartain/Desktop/WIP/results"

os.makedirs(OUTPUT_DIR, exist_ok=True)

def analyze_phone_audio(audio_path):
    if audio_path is None:
        return "Please record or upload an audio file first!"

    old_files = glob.glob(os.path.join(OUTPUT_DIR, "*.txt")) + glob.glob(os.path.join(OUTPUT_DIR, "*.csv"))
    for f in old_files:
        try:
            os.remove(f)
        except:
            pass

    print(f"Analyzing audio file via birdnet-analyze command tool...")

    try:
        subprocess.run([
            "birdnet-analyze",
            "--classifier", MODEL_FILE,
            "--output", OUTPUT_DIR,
            "--min_conf", "0.10",
            audio_path
        ], check=True)

        result_files = glob.glob(os.path.join(OUTPUT_DIR, "*.txt")) + glob.glob(os.path.join(OUTPUT_DIR, "*.csv"))

        if result_files:
            result_file = result_files[0]
            mountain_lion_detected = False
            high_confidence_matches = []

            with open(result_file, "r") as f:
                reader = csv.DictReader(f, delimiter="\t")

                for row in reader:
                    confidence = float(row.get("Confidence", 0))
                    species = row.get("Common Name", "") or row.get("Scientific Name", "")

                    if confidence >= 0.40:
                        mountain_lion_detected = True
                        start_time = row.get("Start (s)", "N/A")
                        end_time = row.get("End (s)", "N/A")
                        high_confidence_matches.append((start_time, end_time, confidence, species))

            if mountain_lion_detected:
                verdict = "HIGH POSSIBILITY OF MOUNTAIN LION DETECTED! (Confidence >= 0.40)\n\n"
                verdict += "Detections:\n"
                for start, end, conf, sp in high_confidence_matches:
                    verdict += f" • [{start}s - {end}s] Species: {sp} | Confidence: {conf:.2%}\n"
                return verdict
            else:
                return "NO HIGH LIKELIHOOD DETECTED\n(No detections above 0.40 confidence)."

        else:
            return "Analysis finished, but no output data file was generated by BirdNET."

    except subprocess.CalledProcessError as e:
        return f"Analysis command failed. Error details: {str(e)}"
    except Exception as e:
        return f"App error: {str(e)}"

interface = gr.Interface(
    fn=analyze_phone_audio,
    inputs=gr.Audio(sources=["microphone"], type="filepath"),
    outputs=gr.Textbox(label="Analysis Verdict", lines=6),
    title="Mountain Lion Acoustic Detection System",
    description="Record audio on your mobile device. The system triggers birdnet-analyze instantly to track matching signatures."
)

if __name__ == "__main__":
    interface.launch(share=True)
